// @flow

const BLUE_SEA = '#317AF7';
const BORDER = '#E5E5E5';
const BORDER_ACTIVE = '#4080D7';
const ICON_COLOR = '#235ba8';
const GREY = '#EDAADF';
const LIGHT_BORDER = '#FAFAFA';
const LIGHT_GREY = '#DFDFDF';
const LIGHT_PURPLE = '#7BAAF9';
const MAIN_TEXT = '#61656A';
const WHITE = '#FFFFFF';

export {
  BORDER,
  BORDER_ACTIVE,
  BLUE_SEA,
  GREY,
  ICON_COLOR,
  LIGHT_BORDER,
  LIGHT_GREY,
  LIGHT_PURPLE,
  MAIN_TEXT,
  WHITE,
};
